# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vietnam-dply
  namespace: dailybruin-sub
  labels:
    app: vietnam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vietnam
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: vietnam
      labels:
        app: vietnam
    spec:
      containers:
      - name: vietnam-php
        image: dailybruin/vietnam-php:staging
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 150m
            memory: 230Mi
          limits:
            cpu: 250m
            memory: 300Mi
        ports: 
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always
---
# Service

apiVersion: v1
kind: Service
metadata:
  name: vietnam-svc
  namespace: dailybruin-sub
  labels:
    app: vietnam-php
spec:
  selector:
    app: vietnam
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
#Ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: flamingo-tls
  name: vietnam-php-ingress
  namespace: dailybruin-sub
spec:
  ingressClassName: nginx
  rules:
  - host: vietnam.dailybruin.com
    http:
      paths:
      - backend:
          service:
            name: vietnam-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - vietnam.dailybruin.com
    secretName: flamingo-tls